### PR TITLE
Support for building docs using gitbook added.

### PR DESCRIPTION
**Pull request by lxsameer**
This PR add the support for building the current docs using `gitbook` tool. install `gitbook-cli` using `yarn` or `npm` and just run:
```
npm run build
```
the result would be under `docs/build`.
**IMPORTANT NOTE**: In order to create epub, mobi, and pdf files you need to install `Calibre` and set it up properly. 

for more info checkout: https://toolchain.gitbook.com/ebook.html

### CODE REVIEW

**Comment by danielcompton** [comment]
Do you have a link from building this on your own fork so we can see what this will look like?

**Comment by lxsameer** [comment]
I'll upload them in my `gh-pages` branch and paste the link

**Comment by lxsameer** [comment]
here is the link to my `gh-pages` . sorry for the custom domain ( I messed up my configuration and didn't have time to fix it).

http://re-frame.lxsameer.com
http://re-frame.lxsameer.com/re-frame.pdf
http://re-frame.lxsameer.com/re-frame.mobi
http://re-frame.lxsameer.com/re-frame.epub

Also please not that this is not 100% done. We still need to tweak the docs a little bit and rearrange the structure to be much nicer. but it gives you an idea about the bigger picture.

**Comment by mike-thompson-day8** [comment]
Thanks!

**Comment by danielcompton** [comment]
This is live at https://d8.gitbooks.io/re-frame/content/

**Pull request merged**
