### PR TITLE
Edits to examples doc

### PR DESCRIPTION
**Pull request by richardharrington**
Some minor but fairly widespread changes to the documentation for the "simple" example. Feel free to take or leave any of them.

Note: I have no preference on British vs. American spelling, but I made the docs American (-ize instead of -ise) to match the spelling in the keywords in the code.

Another note: I ran doctoc. It made major changes to files I never touched. They look ok, but you're welcome to kill that commit.

### CODE REVIEW

**Comment by danielcompton** [comment]
All looks good, though I think I'll revert the American English changes, will check with Mike.

**Comment by richardharrington** [comment]
Thanks!

If you revert the American English changes, make sure that either 1) You don't revert the ones that are actual code samples, or 2) You also change all `:initialize` keywords throughout the code to `initialise`.

**Comment by danielcompton** [comment]
Thanks, I took the first option.

**Comment by richardharrington** [comment]
Cool!

**Pull request merged**
