### PR TITLE
Improve reg-sub documentation

### PR DESCRIPTION
**Pull request by urzds**
Coming from #516 I tried to make the syntax sugar documentation of `reg-sub` easier to understand for newcomers.

### CODE REVIEW

**Comment by urzds** [comment]
This should be treated as a WIP, until I can get a preview of the new docs and confirm they look as intended (cljdoc/cljdoc#236).

**Comment by mike-thompson-day8** [comment]
@urzds  Thanks for this.  I'm happy to merge and then we can incrementally fix any further issues as they are identified.  What do you think?

**Comment by urzds** [comment]
ACK. Sorry, haven't had the time to test the cljdoc generation output locally.

**Comment by mike-thompson-day8** [comment]
Thanks!

**Comment by mike-thompson-day8** [comment]
Okay, so I ended up making one or two tweaks, and, before I knew it, I had performed significant surgery to both your new stuff and all my old stuff.  I hope it is now clearer. But all mistakes are now mine to own :-)  Thanks for pushing me to improve this.

**Comment by urzds** [comment]
Thanks!

**Pull request merged**
