### PR TITLE
Add interceptor error handling

### PR DESCRIPTION
**Pull request by nberger**
As discussed in #231, this allows for handling exceptions as part of the interceptor chain. It's inspired (the same as the overall interceptors implementation) by how pedestal handles exceptions in its interceptors. It gives the possibility to handle exceptions as early as possible (as opposed to a window.onerror handler), with much as context as possible

### CODE REVIEW

**Comment by danielcompton** [comment]
Thanks for this. I've taken a first pass over this and it looks pretty good. I'm still digesting the tests, and noodling on introducing the `:error` stage. I also need to take another look at the tests to make sure I grasp everything that's going on there. Have you thought about how this might be described in the docs? I'm not asking you to redo it all now, as we may still go another way on this, but I'm curious as to how we document it.

The main use case I've heard for this so far is for error reporting. re-frame doesn't really encourage using exceptions for flow control in quite the same way as Pedestal's interceptors do, nor do we really intend to handle exceptions from event handlers and continue executing an event. I'm wondering about a more limited approach here instead:

1. Register an error reporter, e.g. `re-frame.core/register-event-error-handler`
2. Run all interceptors in a try/catch
3. If an error occurs, call the error reporter with an exception created by your `exception->ex-info` and abort event processing

I'm aware this approach is a little more primitive, but it doesn't change the interceptor pipeline by introducing a new stage concept. Would this work for your use case? What's your thought on this alternate proposal?

**Comment by nberger** [comment]
@danielcompton: thanks for taking a look.

I actually like your alternative "limited" approach. It would work well for us. And I agree, error reporting/logging seems to be the common use case. The semantics of this error handler would be much simpler so it would also be easier to describe in the documentation. Even though I'll keep thinking about it, I don't have any objection to following that path.

**Comment by nberger** [comment]
@danielcompton I'm still interested on this, but couldn't find the time to work on it lately since I haven't been using re-frame that much. I could try and resolve the conflicts here but the idea is to implement the more simple approach that you proposed, right?

I still think this is an important feature: having a clean way to catch exceptions in the interceptors/handler chain. Even though I haven't been following the latest additions I think this is somewhat missing, right?

**Comment by nberger** [comment]
Closed in favor of #423

**Pull request closed without merging**
