### PR TITLE
Upgrade reagent to 1.0.0

### PR DESCRIPTION
**Pull request by mthl**
https://github.com/reagent-project/reagent/commit/02f209810b482d14a3e2af20d325bdf0cbf51e5e

### CODE REVIEW

**Comment by superstructor** [comment]
@mthl Thanks for the PR. How much have you tested this ? How complex are the apps/examples that you have tested ?  

It looks like quite a major upgrade looking at the [reagent CHANGELOG](https://github.com/reagent-project/reagent/blob/master/CHANGELOG.md#100-2020-12-21).

**Comment by mthl** [comment]
Testing has been limited on my side, I used re-frame 1.1.2 with reagent 1.0.0 for a webapp internally in my company for a month for a "small" application without noticing any issue, but this is not like saying that I am confident that there is no regression.

In terms of automated testing I have simply  run `lein test` before submitting my PR.

Thanks for you quick feedback.

**Comment by superstructor** [comment]
Thanks @mthl , this is waiting on us to look at day8/re-frame-10x#275

**Comment by superstructor** [comment]
I've released re-frame-10x 1.0.0 with reagent 1.0.0 support, so we can now proceed.

**Pull request merged**
