### PR TITLE
Minor code cleanup

### PR DESCRIPTION
**Pull request by ducky427**

### CODE REVIEW

**Comment by danielcompton** [comment]
LGTM, I'll let @mike-thompson-day8 approve before merging though.

**Comment by ducky427** [comment]
Thanks.

**Comment by danielcompton** [comment]
This looks fine to me, @mike-thompson-day8 can revert if he doesn't like the style.

**Comment by danielcompton** [comment]
Thanks!

**Comment by ducky427** [comment]
Thanks @danielcompton!

**Pull request merged**
