### PR TITLE
Add a :dispatch-throttle effect #250

### PR DESCRIPTION
**Pull request by kp2222**
These changes are mostly based on a similar pull request for debounced events #249

### CODE REVIEW

**Comment by danielcompton** [comment]
Thanks heaps for this, I especially appreciate the extensive tests :) Will take me a little bit to give it a proper review, but hope to get to it soon. If you have time, would you be able to add some docs to Effects.md for this? Otherwise I can add them. Thanks!

**Comment by kp2222** [comment]
Thanks for the quick reply. Here are the docs :)

**Comment by lsnape** [comment]
My expectations are that `dispatch-throttle` defers any event from being handled until after `window-duration` milliseconds has elapsed. But with this implementation that behaviour only holds true if more than 1 event is queued at one time. Unless the events are queued synchronously it is likely that they will always be dispatched immediately. I think you need to persist a `last-ran` timestamp so that you know when the last event occurred.

Thanks for taking the time to write this PR – Looking forward to using this. 👍

**Comment by kp2222** [comment]
what do you mean by 
> "dispatch-throttle defers any event from being handled until after window-duration milliseconds has elapsed. But with this implementation that behavior only holds true if more than 1 event is queued at one time" ?  

Doesn't this test case cover this scenario?

```
(deftest dispatch-throttle-only-trailing
  (async done
         (go
           (let [seen-events (atom [])
                 throttled-event (fn[event]
                                   {:id ::dispatch-throttle-only-trailing
                                    :window-duration 50
                                    :leading? false
                                    :trailing? true
                                    :dispatch [::type-ahead-search event seen-events]})]
             (re-frame/dispatch [::throttle-test (throttled-event "a")])
             (<! (timeout 10))
             (is (= @seen-events []))
             (<! (timeout 60))
             (is (= @seen-events ["a"]))
             (done)))))
```

The behavior of the first event getting dispatched immediately can be turned off by setting leading? to false. Of course, I might be missing something completely here. I am happy to work on the changes once I figure out the issues are :)

**Comment by lsnape** [comment]
OK, understood! I think I've found the source of my confusion: to my mind, throttling is the process by which events are prevented from dispatching too quickly so an not to overwhelm another part of the system. It doesn't drop events, only defers them from running quicker than the interval specified. 

I see now that your implementation is something different: you're only setting the last seen event in the `throttled-events` atom and using `leading?`, `trailing?` and `window-duration` to determine when that should be run.

Would it not make more sense to accumulate the events, rather than only defer the last seen event? After all, it's still possible to cancel older / newer events in the handler of the deferred event itself.

I'd be interested to hear your / anyone elses thoughts! :)

**Comment by kp2222** [comment]
Ah, I see what you were saying now :) However, I can't think of a way to implement event throttling without dropping the events.

The problems I see in implementing something like this is :

* This would require an unbounded queue (so we don't drop any events). Unbounded queues are almost always a bad idea.

* Assuming we keep an unbounded queue of events, as the queue starts getting bigger the recent events will have to wait too long before dispatched and I can't think of  any actual use case where this would be useful.

In addition to this, we were looking at lodash's  implementation of [throttle](https://lodash.com/docs/4.16.6#throttle) as a reference implementation.

**Comment by danielcompton** [comment]
> to my mind, throttling is the process by which events are prevented from dispatching too quickly so as not to overwhelm another part of the system. It doesn't drop events, only defers them from running quicker than the interval specified.

The intent of this effect handler is to provide something similar to lodash's throttle. I can see why you might want something like what you're describing, but this isn't it :)

**Comment by lsnape** [comment]
OK, thanks for bearing with me. I've now implemented my own fx for what I want - really easy to do in the end :)

One last suggestion: do you want to ensure that no throttled events are handled after a `:cancel` action is received? If so then I think a `dispatch-sync` is needed (though not entirely sure what the drawbacks are to this approach).

Cheers

**Comment by Latros** [comment]
Nice work @kp2222, looking forward to using this

**Comment by danielcompton** [comment]
After talking with @mike-thompson-day8 we've decided we'd prefer to keep this and #249 as separate FX handlers that aren't part of re-frame core. They'll still be advertised like other effects in libs so people can learn about them. This is mainly as people have different preferences for these kinds of FX, to reduce the maintenance burden on re-frame, and that they probably don't belong as part of the [naked robotic core](http://5by5.tv/hypercritical/86) of re-frame. 

@kp2222 if you end up putting this PR into a library, I'm happy to add #249 to it as, as debounce and throttle are quite similar.

Sorry for the delay and run-around after inviting PR's for this feature 🙏.

**Comment by avocade** [comment]
+1 for breaking this out in a separate lib.

**Comment by thegeronimo** [comment]
> Add :dispatch-debounce fx handler #249

Did this ever become a library?

**Pull request closed without merging**
