### PR TITLE
self-host compatibility using macrovich

### PR DESCRIPTION
**Pull request by viebel**
This PR makes `re-frame` self-host compatible.
It means that `re-frame` can now be used inside KLIPSE  (which is going super useful for sharing bugs, ideas and more...).
#
Here is a [live demo](http://app.klipse.tech/?container&cljs_in.gist=viebel/e82b197907a7117f72f1a0b9a4a56303).

Note: The self-host compatibility of `re-frame` depends on the self-host compatibility of `re-agent` that is achieved by   https://github.com/reagent-project/reagent/pull/283
image
.

### CODE REVIEW

**Comment by arichiardi** [comment]
Awesome! Also very good for using experimenting with `lumo`

**Comment by danielcompton** [comment]
Thanks for this, I'll need to review this carefully, but it should be ok. Here's the changes without [whitespace diffs](https://github.com/Day8/re-frame/pull/325/files?w=1).

**Comment by viebel** [comment]
Any update on this PR @danielcompton ?

**Comment by danielcompton** [comment]
I'm ok to merge this for now, on the proviso that if it causes any problem in future versions of Clojure/ClojureScript then it'll be pulled out. So you can use it for things, and I don't anticipate us removing it, but at the moment supporting self-hosting is a non-goal, so don't treat it as being officially supported by re-frame.

**Comment by danielcompton** [comment]
Thanks for this!

**Pull request merged**
