### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by yatesco**
Added an example of a subscription based on setup config for form-2 components.

### CODE REVIEW

**Comment by danielcompton** [comment]
This looks really helpful, thanks. I'll give @mike-thompson-day8 a chance to check over this, then I or he can merge it.

**Comment by yatesco** [comment]
Thanks Daniel. After discussing with Mike on Slack I want to add some more words tomorrow.

**Comment by danielcompton** [comment]
@yatesco do you still have more you want to update on this?

**Comment by yatesco** [comment]
Hi Daniel, I sure do, but I still haven't got the time unfortunately. I think this is sufficient as-is. 

When I do get time I shall add some more words around the limitations of form-2 components using subscriptions based on inputs.

**Comment by danielcompton** [comment]
No problems, merged in 27835cf.

**Pull request closed without merging**
